---
name: CI-hadolint
'on':
  schedule:
    - cron: "20 23 15 * *"

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2404
          # - debian12

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.0

      - name: Run Molecule tests.
        run: |
          devbox run -- molecule test -s hadolint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
